### ISSUE TITLE
mergetomoseg.py command not found in EMAN2

### ISSUE THREAD

**Issue by amehrani** [cryoem/eman2#417]
I am using the latest version of EMAN2.2 and I am trying to segment a tomogram using the CNN protocol in EMAN. Annotation works quite fine for most of the features however, in some cases microtubules are being picked as single membrane feature, even after extensive training. In the online instruction it has been suggested to train the neuronal network separately on the features that cause ambiguity and then run annotations against each other using mergetomoseg.py <annotation #1> <annotation #2> <...> --output <output mask file>. However, when I run mergetomoseg.py, I get the error message that the command not found. I am wondering if you have any suggestion for this issue? Is there any replacement for this command in EMAN2.2? 

Thanks very much for your help in advance.

**Comment by sludtke42** [comment]
Hi. EMAN2.3?

that particular program is found in 'examples' rather than 'bin'. It's probably mature enough to move into the main set of tools...

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)

**Comment by amehrani** [comment]
Hi, 
It was in examples directory. Thank you so much for your help.
