### ISSUE TITLE
Questionable detection of 8-bit-packed mode from MRC headers

### ISSUE THREAD

**Issue by jcbollinger** [cryoem/eman2#458]
Having recently engaged in the exercise of building the EMAN2 2.3 release from source, I had the opportunity to analyze compiler warnings to look for any that indicated genuine problems.  There was a lot of noise, but a little signal, all of which appears still to apply to the current head.  I'll be splitting that into four separate issues, of which this is the first.

----

libEM/mrcio.cpp:206-207 is this:

```
		is_8_bit_packed = (mrch.mode == MRC_UHEX       ||
							   (mrch.imod_flags & 16) == 1  ||  double_nx);
```
But the condition `(mrch.imod_flags & 16) == 1` never evaluates to true, because `anything & 16` always evaluates to either 0 or 16.  From code analysis alone, I suspect that `(mrch.imod_flags & 16) != 0` would be consistent with the intention, but I am not sufficiently familiar with the details of the MRC format to confirm that.

**Comment by sludtke42** [comment]
Hi John,
thanks for taking the time to work on some of these. Periodically when someone has free time, people do browse through the numerous warnings and fix things, but as you have undoubtedly noticed that academic code developed over 15 years with a couple of dozen, not always well-trained, programmers will tend to have its share of little issues :^)

Anyway, we will get the correct person to look at each of these. 

I would suggest that if you're taking the time to do this, you might want to work on master with the Python3 prerelease rather than focusing on a year-old release version. I doubt the two things you've posted have changed, with, but we have moved pretty far past 2.3 at this point :^)

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)

**Comment by sludtke42** [comment]
Resolved on master (not pushed yet)

**Comment by jcbollinger** [comment]
Hi Steve,

That was fast!

I assure you that although I'm working with warnings generated while compiling the latest release version, I am checking the current Git head to verify that the problems appear to still be present there.

Cheers,

John
________________________________

**Comment by sludtke42** [comment]
Ok, no problem :^)

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)
