### ISSUE TITLE
Status of tomo in devel?

### ISSUE THREAD

**Issue by pconesa** [cryoem/eman2#503]
Dear developers, 

How would you describe the status of "Eman 3" (python 3) for tomography code and maybe SPA too?

I'm from Scipion team, and when integrating tomography methods using 2.3.1 some worked, but others not, but they weren't going to be fixed in that version (which if perfectly fine). We tried some months ago "devel" branch here but some methods (template matching) worked but others not.

So, up to now, we are offering 2.31 (without template matching).

I would like to know (roughly is ok) how is this going, would you say is:

fully devel (unstable)
alpha
beta
Other?

All the best, Pablo.

**Comment by sludtke42** [comment]
The first Python 3 release of EMAN 2 will not be EMAN 3, as it remains fundamentally the same package as EMAN 2, though we are heading in that direction. Our plan was to release the Python 3 version many months ago, but SPHIRE has taken a bit longer to get their Python 3 support in place, and we have been continuing to develop other tools as well, so it keeps getting pushed back. I'd like to say "any day now". 

Anyway, the subtomogram averaging pipeline in the current EMAN '2.39' snapshot versions is very stable at this point, and has been being used for production research for pretty much all of 2020. Yes we continue to improve things, but this is largely in the form of feature additions, rather than bugfixes. You _definitely_ should not be using the subtomogram pipeline in 2.31. While it is relatively stable, it lacks many of the tools we have been discussing over the last year, and definitely has bugs. 2.39 right now is quite stable.

**Comment by pconesa** [comment]
Many thanks for the extensive detailed explanation @sludtke42 .
Is 2.39 the latest release here? (May 2019, github)
Or here: https://cryoem.bcm.edu/cryoem/downloads/view_eman2_version/30

All I see everywhere is 2.31. Sorry if this is too obvious.

**Comment by sludtke42** [comment]
This is the current snapshot binary (updated by the developers when they think they have made an important (stable) change):
https://cryoem.bcm.edu/cryoem/downloads/view_eman2_version/25 <https://cryoem.bcm.edu/cryoem/downloads/view_eman2_version/25>

We advise people working with prereleases to install from source if possible, so they can trivially update if necessary. The source installation (Mac and Linux) is almost as easy as the binary installation. Just follow the step by step instructions.

**Comment by pconesa** [comment]
Many thanks!
